apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nexus-iq-backendconfig
  namespace: nexus-iq
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    type: HTTP
    requestPath: /ping
