apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-iq-pvc
  namespace: nexus-iq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2560Gi
  storageClassName: ""
  volumeName: nexus-iq-filestore-pv
