apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-iq-filestore-pv
spec:
  capacity:
    storage: 2560Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: FILESTORE_IP_PLACEHOLDER
    path: /nexus_iq_ha_data
