apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iq-server-pvc
  namespace: nexus-iq
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi
