apiVersion: batch/v1
kind: Job
metadata:
  name: nexus-iq-migrate-db
  namespace: nexus-iq
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: nexus-iq-migration
        image: sonatype/nexus-iq-server:1.195.0
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting database migration..."
          java -jar /opt/sonatype/nexus-iq-server/nexus-iq-server.jar migrate-db config.yml
        env:
        - name: NXIQ_DATABASE_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: nexus-iq-server-ha-iq-server-database-hostname-secret
              key: hostname
        - name: NXIQ_DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: nexus-iq-server-ha-iq-server-database-port-secret
              key: port
        - name: NXIQ_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: nexus-iq-server-ha-iq-server-database-name-secret
              key: name
        - name: NXIQ_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: nexus-iq-server-ha-iq-server-database-username-secret
              key: username
        - name: NXIQ_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-iq-server-ha-iq-server-database-password-secret
              key: password
        volumeMounts:
        - name: nexus-iq-config
          mountPath: /opt/sonatype/nexus-iq-server/config.yml
          subPath: config.yml
          readOnly: true
      volumes:
      - name: nexus-iq-config
        configMap:
          name: nexus-iq-server-ha-iq-server-config-configmap