[PARSER]
    Name         iq_request
    Format       regex
    Regex        ^(?<client_host>[^ ]*) (?<ident>[^ ]*) (?<auth_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>[^ ]*) (?<path>[^ ]*) (?<protocol>[^"]*)" (?<status>[^ ]*) (?<bytes>[^ ]*) (?<elapsed_time>[^ ]*) "(?<user_agent>[^"]*)"$
    Time_Key     time
    Time_Format  %d/%b/%Y:%H:%M:%S %z
    Types        status:integer bytes:integer elapsed_time:integer

[PARSER]
    Name         iq_application_firstline
    Format       regex
    Regex        ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}

[PARSER]
    Name         iq_application
    Format       regex
    Regex        ^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}[+-]\d{4}) (?<level>[^ ]*) \[(?<thread>[^\]]*)\] (?<username>[^ ]*) (?<logger>[^ ]*) - (?<message>.*)$
    Time_Key     timestamp
    Time_Format  %Y-%m-%d %H:%M:%S,%L%z

[PARSER]
    Name         json
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
